### ISSUE TITLE
Exception Running Document Processor '<Paragraph Structure Normalizer>'

### ISSUE THREAD

**Issue by retog** [gsautter/idaho-core#2]
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 37465
        at java.base/java.util.Vector.get(Vector.java:781)
        at de.uka.ipd.idaho.gamta.defaultImplementation.TokenizedCharSequence.tcsTokenAt(TokenizedCharSequence.java:253)
        at de.uka.ipd.idaho.gamta.defaultImplementation.TokenizedCharSequence.tokenAt(TokenizedCharSequence.java:121)
        at de.uka.ipd.idaho.gamta.defaultImplementation.GamtaDocument$AnnotationBase.firstToken(GamtaDocument.java:2224)
        at de.uka.ipd.idaho.gamta.defaultImplementation.GamtaDocument$QueriableAnnotationView.firstToken(GamtaDocument.java:951)
        at de.uka.ipd.idaho.gamta.util.analyzers.ParagraphStructureNormalizer.process(ParagraphStructureNormalizer.java:198)
        at de.uka.ipd.idaho.goldenGate.plugin.analyzers.AnalyzerManager$AnalyzerDocumentProcessor.process(AnalyzerManager.java:202)
        at org.plazi.chflora.App.applyGizmos(App.java:179)
        at org.plazi.chflora.App.main(App.java:113)
  Analyzer initialized
```

**Comment by retog** [comment]
As requested the data I process:
[pre-gizmos.zip](https://github.com/gsautter/idaho-core/files/6849744/pre-gizmos.zip)

**Comment by gsautter** [comment]
Reproduced ... investigating.

**Comment by gsautter** [comment]
The initial intense digging has shown one thing: the one `pageBreakToken` that is off and causes the exception we're observing is broken even before the document comes into the `ParagraphStructureNormalizer` gizmo ... expanding the search radius ...

**Comment by gsautter** [comment]
And the mystery is solved ... turns out the only error on the part of the data model was sloppy range checking when adding annotations ... the document in question has a page break marker as the very last element, and the `App` marks a `pageBreakToken` right after each one, which, in that case, is after the end of the document, which just shouldn't be the case ... added proper range checking to the document class now, on to fixing the `App` code ...
